#pragma once

/**
 * @file adapter_api.h
 * @brief C API that each adapter DLL must export.
 *
 * The server loads adapter DLLs and calls these factory functions.
 * Adapters that want to manage other adapters (e.g. HTTP adapter exposing
 * /api/adapters endpoints) receive a ManagementAPI callback struct.
 */

#include <nlohmann/json.hpp>

class TestRunnerService;

// --- Export macro ---
#ifdef _WIN32
#ifdef ADAPTER_EXPORTS
#define ADAPTER_API __declspec(dllexport)
#else
#define ADAPTER_API __declspec(dllimport)
#endif
#else
#define ADAPTER_API __attribute__((visibility("default")))
#endif

/**
 * @brief C callbacks for adapter and resource provider management.
 *
 * Passed to create_adapter() so adapters (like HTTP) can expose
 * management endpoints without crossing C++ ABI boundaries.
 * All allocations/deallocations happen on the server side.
 */
struct ManagementAPI {
    void* context;  ///< Opaque pointer to AdapterManager.

    // ---- Adapter management ----

    /// Load and start an adapter by name.
    bool (*load_adapter)(void* ctx, const char* name, const nlohmann::json& config);

    /// Stop and unload a running adapter.
    bool (*unload_adapter)(void* ctx, const char* name);

    /// Get JSON array of available/running adapters. Caller must free with free_string().
    const char* (*list_adapters)(void* ctx);

    /// Free a string returned by list_* functions. Must be called from the same side.
    void (*free_string)(void* ctx, const char* str);

    // ---- Resource provider management ----

    /// Load and start a resource provider by name. On failure, error is logged server-side.
    bool (*load_resource_provider)(void* ctx, const char* name, const nlohmann::json& config);

    /// Stop and unload a resource provider.
    bool (*unload_resource_provider)(void* ctx, const char* name);

    /// Get JSON array of all resource providers (available + running). Caller must free.
    const char* (*list_resource_providers)(void* ctx);

    /// Get JSON array of available (not yet loaded) resource providers. Caller must free.
    const char* (*list_available_resource_providers)(void* ctx);

    // ---- Adapter config update ----

    /// Merge extra fields into a loaded adapter's stored config.
    /// Adapters use this to register runtime-generated values (e.g. authToken).
    void (*update_adapter_config)(void* ctx, const char* name, const nlohmann::json& patch);
};

// Factory functions (adapter_name, create_adapter, destroy_adapter) are
// generated by the REGISTER_ADAPTER() macro — see register_adapter.h.