#pragma once

/**
 * @file adapter_api.h
 * @brief C API that each adapter DLL must export.
 *
 * The server loads adapter DLLs and calls these factory functions.
 * Adapters that want to manage other adapters (e.g. HTTP adapter exposing
 * /api/adapters endpoints) receive a ManagementAPI callback struct.
 */

#include <nlohmann/json.hpp>

class TestRunnerService;

// --- Export macro ---
#ifdef _WIN32
#ifdef ADAPTER_EXPORTS
#define ADAPTER_API __declspec(dllexport)
#else
#define ADAPTER_API __declspec(dllimport)
#endif
#else
#define ADAPTER_API __attribute__((visibility("default")))
#endif

/**
 * @brief C callbacks for adapter management (load/unload/list).
 *
 * Passed to create_adapter() so adapters (like HTTP) can expose
 * management endpoints without crossing C++ ABI boundaries.
 * All allocations/deallocations happen on the server side.
 */
struct ManagementAPI {
    void* context;  ///< Opaque pointer to AdapterManager.

    /// Load and start an adapter by name.
    bool (*load_adapter)(void* ctx, const char* name, const nlohmann::json& config);

    /// Stop and unload a running adapter.
    bool (*unload_adapter)(void* ctx, const char* name);

    /// Get JSON array of available/running adapters. Caller must free with free_string().
    const char* (*list_adapters)(void* ctx);

    /// Free a string returned by list_adapters(). Must be called from the same side.
    void (*free_string)(void* ctx, const char* str);
};

// Factory functions (adapter_name, create_adapter, destroy_adapter) are
// generated by the REGISTER_ADAPTER() macro — see register_adapter.h.